In [58]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [59]:
# 读取数据
data = pd.read_csv('../Resource/Harlington_clean.csv')

In [60]:
# 准备数据
air_temp = data['air_temp'].values # 温度数据
o3 = data['o3'].values # 臭氧数据
no2 = data['no2'].values # 二氧化氮数据
no = data['no'].values # 一氧化氮数据

In [61]:
print(air_temp[:5])
print(o3[:5])
print(no2[:5])
print(no[:5])

[4.97765241 5.01267906 5.05103962 5.0996309  5.15642346]
[58.31916164 57.65957454 57.03837684 56.43579479 55.82770424]
[17.16265361 17.8366843  18.46117815 19.06832447 19.68321855]
[5.53685337 5.71771789 5.89544914 6.07272127 6.25027861]


In [62]:
# 将数据转换成LSTM可用的格式
X = np.column_stack((air_temp[:-1], o3[:-1], no2[:-1], no[:-1])) # 输入特征
y = air_temp[1:] # 输出目标

In [63]:
print("变量",X) # [air_temp,o3,no2,no]
print("目标值",y)
print(air_temp[-1])

变量 [[ 4.97765241 58.31916164 17.16265361  5.53685337]
 [ 5.01267906 57.65957454 17.8366843   5.71771789]
 [ 5.05103962 57.03837684 18.46117815  5.89544914]
 ...
 [ 3.22798162  3.78940876 39.39854998 11.47427855]
 [ 3.20851431  3.67970631 39.51989273 11.22706376]
 [ 3.19211734  3.61212752 39.58173224 10.97787094]]
目标值 [5.01267906 5.05103962 5.0996309  ... 3.20851431 3.19211734 3.17895924]
3.1789592434423555


In [64]:
# 创建LSTM模型
model = Sequential()
model.add(LSTM(50, input_shape=(X.shape[1], 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

In [65]:
# 创建LSTM模型
model = Sequential()
model.add(LSTM(50, input_shape=(X.shape[1], 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

In [66]:
# 使用模型进行预测
last_air_temp = air_temp[-1] # 最近一个月的ET
last_o3 = o3[-1] # 最近一个月的辐射
last_no2 = no2[-1] # 最近一个月的湿度
last_no = no[-1] # 最近一个月的温度
last_data = np.array([[last_air_temp, last_o3, last_no2, last_no]])
last_data = np.reshape(last_data, (1, last_data.shape[1], 1))
predicted_et = model.predict(last_data)

print("预测的air_temp值为:", predicted_et)

1/1 [==============================] - 0s 265ms/step
预测的ET值为: [[0.97520983]]
